vim.opt.backup = true,
vim.opt.clipboard = "unnamedplus",
vim.opt.completeopt = { "menuone", "noselect" },
vim.opt.cursorline = true,
vim.opt.expandtab = true,
vim.opt.fileencoding = "utf-8",
vim.opt.ignorecase = true,
vim.opt.mouse = "a",
vim.opt.number = true,
vim.opt.pumheight = 10,
vim.opt.scrolloff = 8,
vim.opt.shiftround = true,
vim.opt.shiftwidth = 4,
vim.opt.shortmess:append("c")
vim.opt.showmode = false,
vim.opt.sidescrolloff = 8,
vim.opt.signcolumn = "yes",
vim.opt.smartcase = true,
vim.opt.smartindent = true,
vim.opt.splitbelow = true,
vim.opt.splitright = true,
vim.opt.tabstop = 4,
vim.opt.termguicolors = true,
vim.opt.undofile = true,
vim.opt.wrap = false,

vim.cmd("set whichwrap+=<,>,[,],h,l")
vim.cmd([[set iskeyword+=-]])
vim.cmd([[set formatoptions=cro]]) -- TODO: This doesn't seem to work
