#!/usr/bin/env bash

# Define desktops
bspc monitor -d {1,2,3,4,5}

### Visual options
bspc config initial_polarity first_child
bspc config split_ratio 0.6
bspc config border_width 2
bspc config window_gap 2
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# Rules
bspc rule -r '*'

bspc rule -a Emacs state=tiled
bspc rule -a feh state=floating
bspc rule -a Firefox desktop='^2'
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a 'Emacs:emacs-everywhere' state=floating sticky=on
bspc rule -a '*:scratch' state=floating sticky=on border=off rectangle=1000x460+480+620

bspc config normal_border_color "#181a23"
bspc config active_border_color "#181a23"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
bspc config top_padding 0
bspc config bottom_padding 34

sxhkd &
"$XDG_CONFIG_HOME"/polybar/run.sh &
