#!/usr/bin/env bash

bspc monitor -d {1,2,3,4,5}

# Rules
bspc rule -r '*'

bspc rule -a Emacs state=tiled
bspc rule -a feh state=floating
bspc rule -a Firefox desktop='^2'
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a 'Emacs:emacs-everywhere' state=floating sticky=on
bspc rule -a '*:scratch' state=floating sticky=on center=on border=off rectangle=1000x800+0+0

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#181a23"
bspc config active_border_color "#181a23"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
bspc config top_padding 0
bspc config bottom_padding 34

sxhkd &
