library: ~/.cache/beets/library.db
directory: ~/music

plugins:
  - acousticbrainz
  - badfiles
  - bandcamp
  - chroma
  - duplicates
  - embedart
  - fetchart
  - fromfilename
  - fuzzy
  - info
  - lastgenre
  - mbsync
  - missing
  - mpdstats
  - mpdupdate
  - playlist
  - scrub
  - smartplaylist

playlist:
  auto: yes
  playlist_dir: ~/music/playlists
  relative_to: ~/music/playlists

smartplaylist:
  auto: yes
  playlist_dir: ~/music/playlists
  relative_to: ~/music/playlists
  playlists:
    - name: all.m3u
      query: ""

per_disc_numbering: yes

match:
  #.1 = 90% similarity required. automatically matches above the threshold.
  # Even at the chosen threshold, can be un-intuitive and not automatically select the choice that meets the threshold. There is a GitHub issue for this that I can't find.
  strong_rec_thresh: .1
  # See https://beets.readthedocs.io/en/v1.4.3/reference/config.html#preferred.
  preferred:
    media: ["CD", "Digital Media|File", "Digital Media"]
    countries: ["US", "GB|UK"]
  distance_weights:
    # Should help "quiet" matching. If beets is too eager to match incorrectly and ignore missing tracks, then this creates more work for the user later when they manually correct the matches to a release without the tracks, or find the missing tracks.
    missing_tracks: 10
    unmatched_tracks: 10

ui:
  color: yes

import:
  incremental: yes
  timid: yes
  log: ~/.cache/beets/importer.log
  group_albums: yes
  bell: yes
